# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # Repository interface bindings
    App\Repository\UserRepositoryInterface: '@App\Repository\DoctrineUserRepository'
    App\Repository\OAuth2ClientRepositoryInterface: '@App\Repository\DoctrineOAuth2ClientRepository'
    App\Repository\AccessTokenRepositoryInterface: '@App\Repository\DoctrineAccessTokenRepository'
    App\Repository\RefreshTokenRepositoryInterface: '@App\Repository\DoctrineRefreshTokenRepository'
    App\Repository\AuthorizationCodeRepositoryInterface: '@App\Repository\DoctrineAuthorizationCodeRepository'
    App\Repository\ScopeRepositoryInterface: '@App\Repository\DoctrineScopeRepository'

    # Tag all grant handlers
    App\Service\OAuth2\Grant\ClientCredentialsGrantHandler:
        tags: ['app.oauth2.grant_handler']

    App\Service\OAuth2\Grant\AuthorizationCodeGrantHandler:
        tags: ['app.oauth2.grant_handler']

    App\Service\OAuth2\Grant\RefreshTokenGrantHandler:
        tags: ['app.oauth2.grant_handler']

    # Configure OAuth2Service to receive tagged grant handlers
    App\Service\OAuth2\OAuth2Service:
        arguments:
            $grantHandlers: !tagged_iterator app.oauth2.grant_handler

    # Configure custom name converter for serializer
    app.serializer.name_converter:
        class: Symfony\Component\Serializer\NameConverter\MetadataAwareNameConverter
        arguments:
            - '@serializer.mapping.class_metadata_factory'
            - !service
                class: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
